# Generated by Django 4.0.4 on 2022-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_words_arabicdesc_words_englishdesc_words_frenchdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='ArabicDesc',
        ),
        migrations.RemoveField(
            model_name='words',
            name='EnglishDesc',
        ),
        migrations.RemoveField(
            model_name='words',
            name='FrenchDesc',
        ),
    ]
